window.__ALIFE_CONTENT__ = window.__ALIFE_CONTENT__ || {};
window.__ALIFE_CONTENT__['zone3:en'] = [
  {
    "id": "ancient-dreams-mechanical-wonders",
    "title": "Ancient Dreams & Mechanical Wonders",
    "body": "<p>The desire to create life from scratch is almost as old as human thought itself. Long before anyone had the word \"technology\", people were already imagining it: clay figures animated by divine words, bronze giants forged by gods, statues that could move and speak. These were all expressions of a question that still sits at the heart of ALife today: <strong>what would it actually take to make something alive?</strong></p>\n<p>First, intricate engineering tried to tackle this question. <a href=\"https://en.wikipedia.org/wiki/Hero_of_Alexandria\">Heron of Alexandria</a>, working in the 1st century AD, devised steam-powered engines and mechanical birds that could sing and move. These were remarkable feats of engineering for the ancient world. Fourteen centuries later, <a href=\"https://en.wikipedia.org/wiki/Leonardo_da_Vinci\">Leonardo da Vinci</a> sketched out a <a href=\"https://en.wikipedia.org/wiki/Leonardo%27s_robot\">clockwork knight</a> capable of sitting up, waving its arms, and moving its jaw. And perhaps most famously, the French inventor <a href=\"https://en.wikipedia.org/wiki/Jacques_de_Vaucanson\">Jacques de Vaucanson</a> unveiled a life-sized mechanical duck in 1739 that could quack, drink water, and simulate digestion.\n</p>\n<p>We understand that none of these automata were truly alive, of course. But they did begin to show us that some of the behaviours we associated with living things — movement, responding to the environment, even feeding — could be isolated, replicated, and even studied. Perhaps the mystery of life, then, was just an engineering problem.\n</p>",
    "wrapCard": true
  },
  {
    "id": "from-automata-to-algorithms",
    "title": "From Automata to Algorithms",
    "body": "<p>The next leap was more radical. In the mid-20th century, a handful of thinkers began to argue that you didn't need a physical body to study life at all. The real essence of living systems, they suggested, wasn't in their materials: it was in their logic. There was a shift away from the purely physical nature of life, towards understanding its underlying computational and informational processes.\n\n<p><a href=\"https://en.wikipedia.org/wiki/Alan_Turing\">Alan Turing</a> showed in the 1930s and 40s that any process that could be described precisely enough could, in principle, be computed. This was a powerful, if not slightly strange, idea. It meant that the step-by-step processes of biology — cell division, inheritance, growth — might be expressible as programs. Turing went further, proposing a model of <a href=\"https://en.wikipedia.org/wiki/Turing_pattern\">morphogenesis</a> (i.e. how organisms develop their physical forms) based purely on the interactions of simple chemical signals. It was one of the first serious attempts to explain a biological phenomenon through computation.</p>\n<p><a href=\"https://en.wikipedia.org/wiki/John_von_Neumann\">John von Neumann</a> took a different angle, working out the theoretical design for a machine that could build complete copies of itself: a computational mirror of biological reproduction. His <a href=\"https://en.wikipedia.org/wiki/Von_Neumann_universal_constructor\">self-reproducing automata</a>, known as a universal constructor, remain a foundational concept in ALife. Then in 1970, mathematician <a href=\"https://en.wikipedia.org/wiki/John_Horton_Conway\">John Horton Conway</a> introduced a deceptively simple program: the <a href=\"https://conwaylife.com/\">Game of Life</a>, a grid of cells each either \"on\" or \"off\" (or \"alive\" or \"dead\", or \"1\" or \"0\"), following three rules about their neighbours. Given the right starting pattern, it could produce structures that moved, replicated, seemed to interact with other structures, and self-organise. None of this was written into the program explicitly. Rather, all of it emerged from the simple rules that Conway had defined. It became one of the most-studied programs in history, and it solidified the idea that complexity didn't need to be designed. Maybe it just needed a few good rules and enough time and space to run.\n</p>\n<p>Between them, these pioneers began to carve out the path for a new way of thinking about life: that it might be understood not just by its material or substrate, but by the abstract computational processes that define it.</p>\n</p>",
    "wrapCard": true
  },
  {
    "id": "the-alife-field-takes-shape",
    "title": "The ALife Field Takes Shape",
    "body": "<p>These ideas had been percolating across mathematics, biology, computer science, and philosophy for decades, but they hadn't yet found a home together. That changed in September 1987, when Langton organised the first Workshop on Artificial Life in Los Alamos, New Mexico.</p>\n<p>No doubt this would have been an unusual gathering, with biologists, computer scientists, physicists, mathematicians, and philosophers, all sat together, united by a shared conviction that life was something you could study by building it, not just observing it. Langton gave this conviction a name: \"life as it could be.\" The vision wasn't to simulate the life we already knew (in biology), but to discover the universal principles behind life in any form. Rather than just dissecting organisms, ALife would try to build them from scratch and study them. Rather than seeking laws that applied only to biology, it would seek laws applicable across different media and substrates. And rather than remaining a scattered set of curiosities across many different disciplines, it would become a community — with its own grand vision, annual conferences, dedicated journals, and research groups worldwide. Some of the people who gathered in Los Alamos that year are still active researchers today — which, in a field obsessed with how things persist and evolve, feels somehow fitting.\n</p>\n<p>Still, this short overview does not do the history of artificial life justice. On the next page, we have a growing interactive timeline showcasing key milestones of artificial life as an idea, scientific field, and community.</p>",
    "wrapCard": true
  },
  {
    "id": "explore-the-alife-timeline",
    "title": "Explore: The ALife Timeline",
    "body": "<p style=\"color:var(--color-muted);margin-bottom:1.25rem;font-size:0.95rem;\">A living, growing <strong style=\"color:var(--color-heading)\">timeline of Artificial Life</strong> \u2014 from ancient automata and the first theoretical machines, through the founding of the field in 1987, to the research happening today. Drag along the timeline, or use the arrows, to travel through the history of ALife.</p><div class=\"interactive-block\">\n<div class=\"interactive-label\">\n<span>\ud83d\udd70 Interactive \u2014 ALife History Timeline</span>\n<a href=\"https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=v2%3A2PACX-1vQoVk-q60bvYNXYS4ntz3-9DJj1heDcaU69hfS5bXoZjr-7Gpr2wcUk89KcvR0MRlwOIoL-6CzJDGvK&font=Default&lang=en&initial_zoom=2&width=100%25&height=650\" rel=\"noopener\" target=\"_blank\">Open full screen \u2197</a>\n</div>\n<div class=\"interactive-wrapper\" style=\"height:650px;\">\n<iframe loading=\"lazy\" sandbox=\"allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox\" src=\"https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=v2%3A2PACX-1vQoVk-q60bvYNXYS4ntz3-9DJj1heDcaU69hfS5bXoZjr-7Gpr2wcUk89KcvR0MRlwOIoL-6CzJDGvK&font=Default&lang=en&initial_zoom=2&width=100%25&height=650\" title=\"ALife History Timeline\"></iframe>\n</div>\n</div><div class=\"callout\" style=\"margin-top:1rem;\"><strong>Tip:</strong> Scroll or drag the band at the bottom to move through time, and click any event to read more. Know a milestone we\u2019ve missed? <a href=\"https://alife-expo.canny.io/\" target=\"_blank\" rel=\"noopener\">Go to feedback board</a> \u2014 the timeline keeps growing.</div>",
    "wrapCard": false
  }
];
