window.__ALIFE_CONTENT__ = window.__ALIFE_CONTENT__ || {};
window.__ALIFE_CONTENT__['zone1:en'] = [
  {
    "id": "welcome",
    "title": "Welcome to Life As It Could Be",
    "body": "<p>What if life isn't only what we see around us: the plants, animals, microbes, and people that we know? What if it was something far stranger and more varied than our current version of the natural world? What if life could be digital, robotic, or built from an entirely different chemistry on a planet we've never visited?</p>\n<p>In fact, how can we determine whether something is “alive” or not? in the first place?</p>\n<p>These are the sorts of questions at the heart of <strong>Artificial Life</strong>, commonly referred to as “ALife”, “Alife”, or “A-Life”. ALife sits at the intersection of biology, computer science, robotics, chemistry, philosophy, cognitive science, and many other disciplines, and concerns itself with the <strong>study and synthesis of lifelike systems</strong>.</p>\n<p>In other words, it doesn't just ask what life <i>is</i>; it asks what life <i>could be</i>.</p>\n<p>Throughout this exhibition, we hope to guide you through the foundations of artificial life. Along the way, perhaps you will engage with an entirely new way of thinking: some of what you see may challenge what you thought you knew about life and living systems. So, prepare to question your assumptions about complex behavior, intelligence, and life itself, and discover how the very essence of these things might not look like you expect</p>\n<p>Your journey into \"life as it could be\" starts here!</p>",
    "wrapCard": true
  },
  {
    "id": "what-is-alife",
    "title": "What is Artificial Life?",
    "body": "<p>In the mid-1980s, computer scientist <a href=\"https://en.wikipedia.org/wiki/Christopher_Langton\">Christopher Langton</a> formally established the field of Artificial Life, defining it as \"the study of artificial systems that exhibit behaviors characteristic of natural living systems.\" The aim of this new field of study was not simply to replicate nature, but rather to use a synthetic approach to discover the universal principles underlying life in <strong>any</strong> form.\n</p>\n<p>Rather than observing and analysing organisms that already exist, ALife researchers might take take inspiration from them and build simplified models or systems from scratch and watch to see whether life-like properties emerge. This sounds straightforward, but it immediately raises hard questions:  What does \"life-like\" actually mean? Which properties are we looking for? Which ones do we ignore? How do we decide? We use many tools — computers and software, robots, chemistry, and even combinations of all these things — to explore some really important questions:</p>\n<ul>\n<li>How do complex and stable patterns emerge from a few simple rules? Think of a flock of birds, where no single bird directs the entire swarm, yet incredible patterns emerge.</li>\n<li>Can intelligence, self-organization, adaptation, and even consciousness emerge without a biological brain or traditional cells? What are the minimum requirements for a system to <i>think</i> or <i>learn</i>?</li>\n<li>What are the <i>absolute minimum</i> ingredients needed for something to be considered alive? How will we know when we see it? Can we find that spark of life in a computer program, a robot, or even a test tube? How do we draw the boundary between a living and non-living system?</li>\n</ul>\n<p>ALife helps us understand the life we already know, and opens up the possibility space for life we haven't yet encountered — on other planets, in our own designs, or somewhere we haven't even imagined yet.</p>",
    "wrapCard": true
  },
  {
    "id": "approach",
    "title": "Building Life to Understand Life",
    "body": "<p>Since traditional biology, chemistry, and physics are limited by only being able to study a single example of life — the ones here on Earth —  they work primarily by observing and analyzing these living systems rigorously. However, Artificial Life gives us a chance to try a different approach: rather than just observing life-as-it-is, we can instead <strong>build it to understand it</strong>.</p>\n<p>Consider a colony of thousands of ants that, with no single leader, collectively find the shortest path to food. The ALife approach is to build one digital ant, give it a few simple rules, release thousands of copies into a simulated environment, and see whether colony-level intelligence emerges on its own. If it does, that tells us something interesting about how real ant colonies work. If it doesn't, we learn something too.</p>\n<p>This synthetic method does two things that pure observation alone cannot. First, it tests our theories: if we believe we understand how something works, we should be able to build it. Second, it lets us venture beyond the life we know. By tweaking the rules, we can ask questions about what life might look like under different environmental conditions, different evolutionary trajectories, or different physical laws. We can simulate thousands of these philosophical thought experiments in just a few hours; the same process in nature takes tens of thousands of years.</p>\n<p>The practical applications are real and growing. ALife-inspired methods have produced <a href=\"https://en.wikipedia.org/wiki/Evolved_antenna\">antenna designs for NASA</a> that no human engineer had thought of, informed <a href=\"https://en.wikipedia.org/wiki/Agent-based_model_of_epidemic_spread\">agent-based models of epidemic spread</a> used in public health policy, and given rise to entire genres of <a href=\"https://en.wikipedia.org/wiki/Generative_art\">generative art</a> that grow and evolve according to their own internal rules. You will see many examples of this later in this exhibition.</p>\n<p>This field is all about pushing the boundaries, not just for the sake of technology, but to deepen our understanding of what life is, how it started and how it works, and how it might exist in the universe.</p>",
    "wrapCard": true
  },
  {
    "id": "interactive",
    "title": "Try It: Conway's Game of Life",
    "body": "<p style=\"color:var(--color-muted);margin-bottom:1.25rem;font-size:0.95rem;\">The <strong style=\"color:var(--color-heading)\">Game of Life</strong> was invented by mathematician John Conway in 1970. Despite having only four simple rules, it produces an astonishing variety of complex, life-like patterns — a perfect first taste of how ALife works. Click cells to bring them to life, start the simulation, and watch what happens \u2014 or load one of the ready-made patterns to see what others have discovered.</p><div class=\"interactive-block\">\n<div class=\"interactive-label\">\n<span>🧫 Interactive — Conway's Game of Life</span>\n<a href=\"https://copy.sh/life/\" rel=\"noopener\" target=\"_blank\">Open full screen ↗</a>\n</div>\n<div class=\"interactive-wrapper\">\n<iframe loading=\"lazy\" sandbox=\"allow-scripts allow-same-origin allow-forms\" src=\"https://copy.sh/life/\" title=\"Conway's Game of Life\">\n</iframe>\n</div>\n</div><div class=\"callout\" style=\"margin-top:1rem;\"><strong>How does it work?</strong> Each cell is either alive or dead. Each generation, four rules determine the next state: underpopulation kills lonely cells, overpopulation kills crowded cells, and cells with just the right neighbours survive or are born. From these four rules, entire self-sustaining “organisms” emerge.</div>",
    "wrapCard": false
  }
];
