window.__ALIFE_CONTENT__ = window.__ALIFE_CONTENT__ || {};
window.__ALIFE_CONTENT__['zone2:en'] = [
  {
    "id": "where-do-you-draw-the-line",
    "title": "Where Do You Draw the Line?",
    "body": "<p>We tend to feel confident that we know life when we see it. A dog is alive; a rock is not. But when we push on that intuition even slightly, things get complicated quickly. The question of <strong>what</strong> makes a system truly alive becomes quite difficult to answer. What makes a dog different to a rock? Is it simply their movement? Growth? Intelligence? Autonomy? Their furry coat? Or is it something deeper? Is there a more fundamental essence that creates the spark of life?</p>\n<p>Scientists, philosophers, and curious minds have grappled with this mystery for centuries, and they're still not fully settled on an answer. The boundary between a <i>living</i> organism and <i>non-living</i> matter is less a clear line than a foggy gradient: the closer you look, the foggier it gets. It gets even more debatable as we discover bizarre new entities on Earth, search for life in the cosmos, or even begin to create our own artificial systems.</p>\n<p>In this zone, we invite you to step into ambiguity. Ask yourself how <strong>you</strong> draw the distinction between something living and non-living — and why. What qualities do you believe are truly essential for a system to be considered alive? How did you decide on them?</p>\n<p>As you continue on, be prepared: the examples and ideas presented here may challenge your gut instinct, and may even make you rethink your definition entirely!</p>",
    "wrapCard": true
  },
  {
    "id": "the-characteristics-of-life-a-scientific",
    "title": "A Scientific View of the Characteristics of Life",
    "body": "<p>To help define and classify the wide variety of \"life\" forms we encounter, scientists often rely on a set of universally accepted (though not always) characteristics. Most of the entities we definitively call <i>alive</i> exhibit <em>all</em> of these properties. If something is missing even one, that entity's \"life status\" becomes a topic of debate!</p>\n<ul>\n<li><strong>Organisation</strong> — Living things are highly ordered and complex, built from specialised components (like cells) that work together in coordinated ways. A single cell is already extraordinarily complex; a multicellular organism is complexity stacked on complexity.</li>\n<li><strong>Metabolism</strong> — Life takes in energy and materials from its environment and transforms them to grow, maintain, and reproduce itself. Whether it's a plant converting sunlight into sugar or an animal digesting a meal, life is, at its core, a continuous chemical process.</li>\n<li><strong>Homeostasis</strong> —  Living systems actively maintain a stable internal environment even as external conditions shift. Your body keeps itself at roughly 37°C whether you're in a heatwave or a blizzard. A fish carefully regulates the salt concentration in its blood even as the ocean's salinity fluctuates around it.</li>\n<li><strong>Growth</strong> — Living organisms increase in size and complexity in an organised way. A seedling becoming an oak, or a single fertilised cell becoming a human being, is more than just an increase in mass — it's a directed, structured unfolding.</li>\n<li><strong>Reproduction</strong> — Life produces more of itself, passing on information to the next generation. This is the mechanism by which life persists through time, and what makes evolution possible.</li>\n<li><strong>Response to Stimuli</strong> — Living things react to their environment. A plant bends toward light. A cat flinches at a loud noise. Even a bacterium tumbles away from a toxic chemical.</li>\n<li><strong>Adaptation</strong> — Over many generations, populations change to better suit their environments. The polar bear's fur, the cactus's water storage, and a bacteria's resistance to antibiotics are the accumulated outcomes of evolution working on variation across time.</li>\n</ul>\n<p>However, many non-living systems can exhibit one or two of these characteristics in interesting, but ultimately superficial, ways. An assembly line uses a blueprint to create identical cars (= reproduction?). A salt crystal grows steadily larger as molecules attach to its surface (= growth?). A motion-sensor light responds to movement in the environment (= response to stimuli?). So, what is missing that prevents them from being considered truly alive?</p>",
    "wrapCard": true
  },
  {
    "id": "the-fringes-that-cause-debate",
    "title": "The Fringes That Cause Debate",
    "body": "<p>The truth is, many interesting systems exist right on the fringes of our definition of life. These are systems that possess <em>some</em> (but not all) of the characteristics we saw previously — and they make it hard for us to decide where to draw the line.</p>\n<p>For example, <a href=\"https://en.wikipedia.org/wiki/Virus\">viruses</a> contain genetic material and can reproduce and evolve — but only by hijacking the machinery of a host cell. They have no metabolism of their own, no cellular structure. Whether they count as alive depends almost entirely on how you define the word. <a href=\"https://en.wikipedia.org/wiki/Crystal\">Crystals</a> grow, self-organise, and can even repair fractures in their structure — but their growth is purely physical accretion, with no genetic information and no reproduction in any meaningful biological sense. <strong>Fire</strong> consumes fuel, grows, and responds dramatically to changes in its environment — perhaps why ancient cultures so readily treated it as a living force — but it has no cells, no genetic code, and doesn't produce offspring.</p>\n<p><a href=\"https://en.wikipedia.org/wiki/Prion\">Prions</a> are a strange case: misfolded proteins that cause other proteins to misfold in the same way, spreading through a system and causing devastating diseases like <a href=\"https://en.wikipedia.org/wiki/Creutzfeldt%E2%80%93Jakob_disease\">CJD</a> and <a href=\"https://en.wikipedia.org/wiki/Scrapie\">scrapie</a>. That's a form of replication, but prions are just molecules, with no cells, no metabolism, nothing beyond that single eerie trick.</p>\n<p>And then, of course, there are artificial systems. As robots become more sophisticated, as AIs learn and adapt, as synthetic biology produces <a href=\"https://www.jcvi.org/research/first-self-replicating-synthetic-bacterial-cell\">cells assembled from scratch</a> in the lab, we face the question again: if an artificial system could genuinely adapt, reproduce, and self-organise without biological components, would we consider it to be alive? What was once sci-fi is now an active area of research and discussion in the ALife community.\n</p>\n<p>In the interactive zone on the next page, you'll encounter images and videos of different systems and phenomena. For each one, consider which of these characteristics are present, which are absent — and where, if anywhere, you'd draw the line.</p>",
    "wrapCard": true
  },
  {
    "id": "where-do-you-draw-the-line-2",
    "title": "Where Do You Draw the Line?",
    "body": "<p style=\"color:var(--color-muted);margin-bottom:1.25rem;font-size:0.95rem;\">In the original expo, visitors were shown images and videos of different systems and asked: <strong style=\"color:var(--color-heading)\">alive or not alive?</strong> Feel free to take part below and record your results!</p><div class=\"interactive-block\">\n<div class=\"interactive-label\">\n<span>🧪 Interactive — Living vs. Non-Living Survey</span>\n<a href=\"https://forms.gle/oT1mT1gkbbnwDsSe7\" rel=\"noopener\" target=\"_blank\">Open in Google Forms ↗</a>\n</div>\n<div class=\"interactive-wrapper\">\n<iframe frameborder=\"0\" height=\"1267\" marginheight=\"0\" marginwidth=\"0\" src=\"https://docs.google.com/forms/d/e/1FAIpQLSd3pbwszRpWmJWDMgiCiw321nq_Yb8ECp506e2CPSwGI-NGnA/viewform?embedded=true\" width=\"640\">Loading…</iframe>\n</div>\n</div><div class=\"callout\" style=\"margin-top:1rem;\"><strong>Note:</strong> If the form doesn't load in this frame, use the <a href=\"https://forms.gle/oT1mT1gkbbnwDsSe7\" rel=\"noopener\" target=\"_blank\">direct link</a> to open it in a new tab.</div>",
    "wrapCard": false
  }
];
